const customDescriptions: { [key: string]: string } = {
    "Grand Theft Auto V": 
      "GTA 5 es la quinta entrega de la exitosa saga de videojuegos sandbox desarrollada por Rockstar Games, Grand Theft Auto. Con millones de ventas a sus espaldas y uno de los mundos abiertos más ricos hasta la fecha, Grand Theft Auto V transporta al jugador a Los Santos, una extensa y soleada\
      metrópolis en declive que lucha por mantenerse a flote en una era de incertidumbre económica y realities baratos que referencia de una forma paródica a la Los Ángeles de nuestro tiempo. En este contexto tan crítico y sarcástico de la sociedad actual, tres criminales muy diferentes barajan\
      sus probabilidades de éxito: Franklin, un estafador callejero en busca de mucho dinero; Michael, profesional ex convicto con un retiro muy diferente al que imaginaba; y por último Trevor, un maníaco violento cuya motivación pasa por encontrar drogas baratas que meterse y propinar nuevos atracos.\
      Los tres unidos crean una banda en la que se lo jugarán al todo o nada para lograr el gran golpe de sus vidas: hacerse ricos. Y es que GTA 5 combina historia y jugabilidad de una nueva forma vista en la serie. Los jugadores entran y salen repetidamente de las vidas de los tres personajes,\
      participando en todos los aspectos de la historia entrelazada del juego.",
    
    "The Witcher 3: Wild Hunt": 
      "RPG de mundo abierto que destaca por su narrativa compleja y su profundo desarrollo de personajes. Siguiendo a Geralt de Rivia, un cazador de monstruos, los jugadores exploran un vasto mundo lleno de decisiones morales y misiones interconectadas. Su sistema de combate estratégico, gráficos\
      impresionantes y una rica ambientación basada en el folclore eslavo lo convierten en una obra maestra. Con múltiples premios, este título elevó el estándar de los RPG modernos. Es curioso que en un juego tan gigantesco y complejo, con tantas y tan buenas historias en su interior, la trama\
      principal sea tan 'sencilla', algo que sobre todo agradecerán los que se estrenen en la saga. Una vez más tomamos el control del carismático brujo Geralt de Rivia, que en esta ocasión anda tras los pasos de Ciri, una especie de hija adoptiva a la que entrenó para convertir en bruja, y que cuenta\
      con unos poderes extraordinarios al ser la portadora de la ‘vieja sangre’. Este es el motivo porque el que está siendo perseguida por la Cacería salvaje, una brigada de caballeros fantasmales que quiere hacerse con los increíbles poderes de Ciri, algo que según una profecía puede acabar con el mundo.",
    
    "Portal 2": 
      "Creado por Valve en 2011, este título combina acertijos innovadores con una narrativa hilarante. Con un puntaje de 95/100, destaca por su diseño de niveles, humor y personajes icónicos como GLaDOS. Su modo cooperativo agrega una dimensión extra para los que buscan desafíos en equipo. Perfecto\
      para quienes disfrutan de juegos de lógica y creatividad. Con la cantidad de secuelas innecesarias que se lanzan todos los años, ¿por qué no íbamos a poder disfrutar de más pistolas de portales dimensionales, afilados diálogos, humor negro y peligros en forma de torretas que amablemente nos saludan\
      antes de acribillarnos? De ahí que Portal 2 sea realmente Portal explotando todo su potencial. Todo cuanto los seguidores echábamos en falta en el primero está en la nueva entrega, y aunque se ha perdido factor sorpresa por el camino, la calidad del juego ensombrece cualquier defecto. Los puzles ya\
      no se limitan a una reordenación de botones o cajas, hay más elementos con los que jugar y experimentar. La historia es un motivo de peso para querer avanzar, realmente hay más que frases referentes a tartas –gag casi eliminado, aunque no totalmente-. Y la duración es mayor, tanto en la historia como\
      en el extra del cooperativo, aunque sabemos que nos quedaremos con ganas de más –y eso es bueno-. Esperemos que la comunidad pueda crear más retos que amplíen la vida durante meses o años.",
    
    "Counter-Strike: Global Offensive": 
      "Lanzado en 2012 por Valve y Hidden Path Entertainment, es un shooter táctico que perfecciona la fórmula que definió la saga. Los jugadores eligen entre terroristas y antiterroristas en intensos enfrentamientos que mezclan estrategia, precisión y trabajo en equipo. Su enorme popularidad en la escena\
      de los eSports se debe a su jugabilidad competitiva, mapas emblemáticos como Dust II y una economía dentro del juego que recompensa decisiones estratégicas. Con una comunidad activa y actualizaciones constantes, CS:GO sigue siendo un pilar del género de disparos. Aquí no encontraréis ni un sistema de\
      progresión por experiencia por el cual conseguir mejoras cada vez más destructivas o armas de precisión milimétrica que os den ventaja por haber jugado más tiempo que alguien que acaba de empezar. Aquí las horas de juego se traducen en más experiencia 'real', somos mejores porque al jugar más hemos\
      aprendido sus mecánicas, el funcionamiento de las armas y los puntos estratégicos del mapa, no porque un sistema nos dé ventajas artificiales. En esencia, Counter-Strike: Global Offensive es el Counter-Strike 1.6 de toda la vida, con un nuevo apartado gráfico para adaptarlo a lo que se pide hoy en día\
      y con algunas mejoras y cambios menores que comentaremos más adelante. Pero a fin de cuentas, lo que tenemos es el mismo juego de siempre. Valve sabe muy bien lo que se trae entre manos, y alterar la fórmula original probablemente habría resultado en las quejas de los fans, quienes a pesar de los años\
      quieren seguir con la fórmula de siempre, la cual por cierto, no ha envejecido para nada y se sigue manteniendo muy en forma.",
    
    "Tomb Raider (2013)": 
      "La franquicia de la que forma parte este nuevo episodio ha pasado por momentos de popularidad extasiante y también por pozos de olvido que parecían no tener fondo. Sin embargo en un momento en el que la industria del videojuego parece sentirse cómoda sólo con nombres reconocibles con kilométricas\
      numeraciones a sus espaldas, los chicos de Crystal Dynamics han tomado una decisión arriesgada aunque con cierta red de seguridad en el salto: el reseteo. Lara Croft nos muestra también en PC cuáles son sus orígenes casi 20 años después de su nacimiento en SEGA Saturn y la primera PlayStation, y el\
      2013 es por fin el año escogido para conocer a la heroína en su juventud y en un momento en el que su vulnerabilidad es máxima. De hecho el primer gran triunfo del nuevo Tomb Raider es el de tratar por fin a su protagonista como un ser humano. Los juegos iniciales de Lara, recordemos, fueron bastante\
      fríos en este sentido por el nulo tratamiento de su carácter y por su imposible figura, y la cosa no mejoró con algunos juegos posteriores donde lo único que separaba a la heroína de ser un rudo marine eran sus voluptuosas curvas. Todo eso cambia en el título que nos ocupa, uno que logra esa difícil\
      tarea de hacernos sentir empatía por algo que en realidad no deja de ser un puñado de píxeles... extraordinariamente renderizados, por cierto.",
  
    "Portal": 
      "Desarrollado por Valve en 2007, revolucionó los juegos de lógica con su diseño innovador y narrativo. Ambientado en las instalaciones de Aperture Science, los jugadores encarnan a Chell, una protagonista silente que debe superar una serie de desafíos con el Portal Gun, una herramienta capaz de crear\
      portales interconectados. La inteligencia artificial GLaDOS aporta un humor negro memorable mientras guía y desafía al jugador con pruebas cada vez más complejas. Aclamado por su diseño minimalista, su narrativa compacta y su enfoque en la física, 'Portal' dejó una huella indeleble en la industria.\
      Dentro del magnífico contenido que ofrece Orange Box, con el segundo episodio independiente de Half Life 2, y la esperada nueva entrega del clásico juego de acción multijugador Team Fortress, destaca la inclusión del original juego de puzles Portal que, con una vista subjetiva, nos propondrá superar una\
      serie de desafíos dentro de las instalaciones científicas de los Laboratorios Aperture, competencia directa del complejo Black Mesa visto en el Half Life original. Lo interesante del asunto es que en este caso, para superar todos estos desafíos, únicamente deberemos valernos de la fantástica arma\
      generadora de portales con la que nos premiarán los gerentes de este peculiar laboratorio, lo que convierte a este título de Valve en una de las apuestas más divertidas del año.",
    
    "Left 4 Dead 2": 
      "Valve regresó en 2009 con este juego de zombis cooperativo. Con un puntaje de 89/100, L4D2 es una experiencia frenética llena de acción y estrategia. Perfecto para jugar con amigos, te mantiene al borde del asiento con su ritmo dinámico y su Director de IA, que hace cada partida única. Si elegimos\
      adentrarnos en el modo campaña, comprobamos que estamos ante cinco nuevos capítulos situados en lugares variados como puede ser un centro comercial, zonas urbanas diversas, pantanos, cementerios o un parque de atracciones. Por supuesto, todos los lugares van a estar repletos de infectados, pero no de esos\
      que arrastran los pies, alzan las manos y se desplazan lentamente para que podamos recargar nuestras armas, apuntar tranquilamente a su cabeza, y abatirlos con frialdad. Left 4 Dead 2 no sería Left 4 Dead 2 si nuestros oponentes no fuesen auténticos atletas sedientos de nuestra carne, tremendamente estúpidos\
      y suicidas, pero con comportamientos salvajes. Su parentesco con los infectados de películas como 28 Días Después o Soy Leyenda es más cercano que con los vistos en sagas como Resident Evil, pese a que los juegos de Capcom cada vez tienden a dar más velocidad a nuestros queridos amigos descerebrados.",
    
    "The Elder Scrolls V: Skyrim": 
      "Bethesda Game Studios lanzó esta épica aventura en 2011, redefiniendo el género de mundo abierto. Aclamado con un 94/100, Skyrim ofrece un vasto mundo lleno de dragones, magia y elecciones impactantes. Es ideal para quienes buscan un RPG inmersivo con una libertad sin igual. Caminamos solos, por el estrecho\
      sendero de una descomunal montaña nevada, en mitad de la noche. Nos dirigimos hacia su cima, en la que se encuentra un lugar sagrado donde esperamos recibir el consejo de unos antiguos sabios, alejados del mundo civilizado. En nuestro largo ascenso tan solo nos cruzamos con algunos animales, ciervos, cabras,\
      que no se perturban demasiado ante nuestra presencia, silenciosos compañeros en esta cerrada noche, en la que también nos acaricia una ligera ventisca. En el cielo, el que podemos ver perfectamente al estar despejado de nubes, dos enormes e hipnóticas lunas nos contemplan, escoltando a un precioso y brillante\
      manto de estrellas. Como telón de fondo a estas excepcionales vistas, la aurora boreal, en unos irracionales tonos verdes, envuelve por completo este escenario de ensueño, y a nuestros oídos, además del sonido de la naturaleza y de nuestras pisadas y respiración, llega una preciosa melodía, que nos transporta\
      por completo a un maravilloso y fantástico mundo, haciéndonos olvidar por unos minutos que tan solo estamos sujetando el mando de una consola frente a un televisor.",
    
    "Red Dead Redemption 2": 
      "Viaja al corazón del salvaje oeste como Arthur Morgan, un miembro de la banda de Van der Linde, enfrentándote a la opresión del gobierno y a las tensiones internas de tu grupo. 'Red Dead Redemption 2' es una experiencia de mundo abierto donde cada decisión tiene consecuencias. La narrativa es profunda, con\
      personajes complejos que exploran temas como la lealtad, el cambio y la naturaleza humana. Su detalle gráfico y la interacción con el entorno ofrecen una de las experiencias más inmersivas que un videojuego ha logrado crear. Un juego en el que cada detalle, cada contenido, está cuidado al milímetro, por lo que\
      disfrutas desde las acciones más mundanas, como tomarte un café por la mañana mientras das los buenos días a tus compañeros de campamento, pescas en un bonito río o juegas una partida de póquer con unos paisanos, hasta los momentos más épicos, como atracar un banco, asaltar un tren en marcha o vivir algunos de\
      los tiroteos más espectaculares que hemos visto nunca. Sin el factor sorpresa del primero, un western que sorprendió a todos en 2010, incluso a los que no simpatizaban con este popular género cinematográfico, esta secuela apuesta por ser mucho más grande y ambiciosa, con una trama principal que dura más de 40 horas,\
      y toneladas de misiones secundarias, actividades, minijuegos, coleccionables y pequeñas historias para poder estar perdidos en su deslumbrante mundo más de un centenar de horas.",
    
    "BioShock Infinite":
      "Año 1912, en la ciudad flotante de Columbia, un hombre llamado Booker DeWitt tiene una misión: rescatar a Elizabeth, una joven con habilidades extraordinarias que podría cambiar el curso de la historia. 'BioShock Infinite' ofrece una combinación de acción intensa, rompecabezas mentales y una narrativa que explora\
      temas filosóficos como el libre albedrío y la justicia. Con gráficos impresionantes y un enfoque en el combate en el aire y en tierra, el juego te arrastra en un viaje que desafía la mente y emociona. Si BioShock fue para muchos el primer gran juego de las actuales consolas, BioShock Infinite viene a poner uno de\
      los últimos broches de oro a esta generación, una obra cumbre dentro de la acción en primera persona, el género más popular en los últimos años. La prolongada espera, con más de cinco años de desarrollo, ha merecido la pena, e Irrational Games ha realizado un juego excepcional, que no decepciona, pese a que las\
      expectativas estaban por las nubes -nunca mejor dicho-. Arrebatadoramente bello, con una ambientación sin igual y una narrativa muy trabajada, en el apartado jugable sí es cierto que no sorprende tanto, a pesar de tratarse de un juego de acción muy divertido y perfectamente ejecutado.",
    
    "Borderlands 2": 
      "Gearbox Software lanzó este shooter de rol en 2012, elevando el estándar del género. Con un 91/100, destaca por su humor excéntrico, armas creativas y un estilo visual único. Es perfecto para los amantes de la acción y las historias irreverentes. Hay muchos elementos roleros, las armas tienen unas complejas\
      estadísticas, a veces causan daños elementales, vemos los puntos de daño que causamos a los enemigos, y obtenemos puntos de experiencia que nos permiten subir de nivel y comprar habilidades, haciendo a nuestro personaje a medida, dentro de las cuatro clases disponibles. Pero sería excesivo decir que es un RPG de\
      acción, es más bien un shooter en mundo abierto con toques de rol, que cogiendo cosas de aquí y de allá, ha creado un género casi nuevo, que todavía nadie se ha atrevido a imitar o replicar, algo que creemos que va a cambiar después del éxito que vaticinamos a esta segunda parte. Realmente Borderlands 2 es una secuela\
      muy continuista, nunca rompe con la mecánica heredada de la primera entrega, y hubiera sido de tontos hacerlo, ya que fue toda una sorpresa y enamoró a millones de jugadores. Su gran logro es ser muy consciente de los errores del primer Borderlands, y atacarlos de manera decidida y directa, sin contemplaciones.\
      Si había algo en él que no os gustaba o que no os terminaba de convencer, excepto su mecánica principal, tened por seguro que en la secuela se ha solucionado o solventado casi por completo. Que los enemigos se hacían repetitivos y poco variados, aquí hay muchos más tipos, que la historia era casi anecdótica, ahora\
      cuenta con una mayor carga narrativa, que las misiones eran poco variadas, ahora da la sensación de que sí lo son. ¿Demasiado desierto? Ahora hay una mayor variedad de escenarios.",
    
    "Life is Strange": 
      "Dontnod Entertainment presentó este innovador juego episódico en 2015. Con un puntaje de 85/100, combina una narrativa emotiva con la mecánica de retroceder en el tiempo. Los jugadores explorarán temas de amistad, pérdida y misterio en una historia que te hará reflexionar. El primer episodio se lanzó el 30 de enero\
      de 2015 para PS4, Xbox One, PC, PS4 y Xbox 360, y ya entonces llamó la atención de muchos su peculiar propuesta, porque lo que en un principio no parecía ser demasiado original, una aventura más a lo Telltale, en el fondo escondía un juego que derrocha personalidad y que se nota hecho con mucho mimo y cariño, algo que\
      demuestra desde el primer minuto. Las aventuras de Max y Chloe fueron ganando cada vez más adeptos, y poco a poco se fue convirtiendo en un título de culto, con una pequeña pero fiel legión de seguidores, que han conseguido hacer mucho ruido a lo largo del año. Tuvimos que esperar hasta el 24 de marzo para disfrutar del\
      segundo episodio, el 19 de mayo llegó el tercero, el cuarto se lanzó el 28 de julio, y la conclusión de la aventura llegó el 20 de octubre con un capítulo final que no terminó de convencer a todos, aunque el cómputo global sea más que satisfactorio. Uno de los mayores obstáculos para que muchos jugadores no lo hayan\
      disfrutado es el idioma, ya que todos los episodios se lanzaron originalmente en inglés, tanto voces como subtítulos, pero ahora llega esta edición física y traducida al español titulada Life is Strange: Limited Edition, que nos parece un completo acierto, aunque eso sí, solo está disponible para Xbox One, PS4 y PC.",
    
    "Half-Life 2": 
      "Valve revolucionó los shooters con este título lanzado en 2004. Con un asombroso puntaje de 96/100, HL2 es una obra maestra de la narrativa interactiva y la física en los videojuegos. Una experiencia imprescindible para los fans de la ciencia ficción. El diseño, para la época, marcó tendencia y mostró, al mismo tiempo,\
      que un juego de estas características no vive sólo de motor gráfico. Posiblemente lo que menos gustó a los jugadores fue el final tan abierto que les esperaba al final del tortuoso camino que habían recorrido y, al mismo tiempo, les emplazaba a una ineludible cita con la continuación que, al fin, ha llegado. Los primeros\
      minutos con este juego, nuestra llegada a la fascistoide Ciudad17, son tan sorprendentes y enigmáticos como lo fueron en el original, y eso, sin duda, promete mucho. No tiene mucho sentido desgranar la trama, ni tan sólo explicar cómo se desencadenan los hechos que dan lugar a la acción, pues es mucho mejor que cada uno lo\
      descubra por sí mismo, muy especialmente cuando estamos ante un juego que logra ofrecer una atmósfera tan elaborada. Los programadores han conseguido orientar todo su poderío gráfico no sólo a la recreación en pantalla de una serie de efectos espectaculares, una iluminación sorprendente, o reflejos inauditos… sí, vale,\
      todo eso está en el juego, pero no es lo que nos va a sorprender realmente, pues el jugador puede asombrarse la primera vez que ve algo de ese tipo, pero las siguientes ocasiones estará condenado a ser algo rutinario y esperable. ",
    
    "BioShock": 
      "El clásico de 2007 creado por 2K Boston te lleva a Rapture, una ciudad submarina que mezcla maravilla y terror. Con un puntaje de 96/100, combina acción, horror y una narrativa filosófica que lo hace único. Ideal para quienes buscan juegos con profundidad temática. En los años 40, un megalómano llamado Andrew Ryan tuvo un\
      sueño. Una ciudad donde el hombre pudiese desarrollarse sin los límites que la política y la religión le han impuesto durante milenios. Una ciudad donde el capitalismo campase libremente y donde la ciencia no tuviese los límites de la moral. Esa ciudad se llamó Rapture y fue edificada bajo el agua, en medio del Océano\
      Atlántico, para ser el nuevo hogar de muchos soñadores dispuestos a abandonarlo todo para embarcarse en esta emocionante utopía. Nada de esto es conocido por el gran público ni por nuestro protagonista, que años después, en 1960, sobrevive milagrosamente a un choque de avión en el Océano cuando se dirigía a Inglaterra,\
      para encontrarse con una misteriosa isla con un sumergible (batisfera) que le lleva a este misterioso lugar donde quizás encuentre refugio. Mientras bajamos a las profundidades de Rapture, nos enteramos de la gran idea. De las limitaciones del hombre y cómo esta ciudad submarina será un nuevo comienzo. Al abrir las puertas\
      de la batisfera y ver la situación, nos damos cuenta de que en el proceso algo ha debido salir mal. La idea era buena, pero en algún momento algo muy grave ha sucedido.",
    
    "Destiny 2": 
      "Bungie lanzó este exitoso shooter en 2017, mejorando la fórmula del original. Con un puntaje de 83/100, Destiny 2 combina una historia épica con contenido cooperativo constante y un multijugador competitivo. Es una opción perfecta para los amantes de la acción en línea. Un juego que pese a sus múltiples defectos fue capaz\
      de enganchar a muchos jugadores durante cientos e incluso miles de horas, porque si algo define a Destiny es lo peligrosamente adictivo que es, algo que se potencia todavía más en esta secuela, en la que es casi imposible soltar el mando. Sí, Destiny 2 es un juego continuista y que no aporta grandes novedades, ni en lo que\
      se refiere a la fórmula jugable ni en cuanto a contenidos verdaderamente originales, ni siquiera hay una nueva raza de enemigos a los que enfrentarnos. En ocasiones parece más una gigantesca expansión del primero que una auténtica secuela, pese a que cuenta con una enorme cantidad de nuevos contenidos en forma de misiones,\
      armas y nuevas localizaciones, y lo que es más importante, arregla de una manera rotunda los mayores problemas del primero. Dicho esto, tenemos el corazón y la mente divididos. Por un lado, tenemos los vicios que nos hemos pegado durante estos días, los divertidísimos ratos que hemos pasado junto a unos amigos pegando tiros,\
      que nos piden recomendaros el juego con entusiasmo y sin reparos, hacía tiempo que no nos lo pasábamos tan bien con un juego de acción en primera persona, enganchándonos a niveles enfermizos. Pero por otro parte nos hubiera gustado que Bungie no solo se dedicara a arreglar y pulir el Destiny original, y que hubieran ido un\
      paso más allá, con un juego más ambicioso, que ofreciera novedades de verdadero peso, que justificaran sin ambages el número dos del título.",
    
    "PAYDAY 2": 
      "Starbreeze Studios presentó este emocionante juego cooperativo en 2013. Con un puntaje de 79/100, PAYDAY 2 ofrece una experiencia intensa donde la planificación y el trabajo en equipo son clave. Perfecto para quienes buscan adrenalina y creatividad en sus partidas. De entrada nos encontramos con que el número de misiones se\
      ha disparado de seis (sin contar los contenidos descargables) a más de 30, algo que de por sí ya garantiza una duración mucho más extensa que en el título original. Al principio de cada una de ellas se nos permitirá deambular por la zona libremente, lo que nos resultará muy útil para detectar donde están las alarmas, cámaras\
      de seguridad, objetivos y todo aquello que pueda suponernos un problema. Una vez creamos tenerlo todo listo, bastará con que nos pongamos la máscara para que comience el golpe. A medida que avancemos en una misión nos irán marcando diferentes objetivos que tendremos que cumplir para superarla, aunque si encontramos algún objeto\
      de valor o dinero extra también podremos agenciárnoslo para aumentar nuestros ingresos al final de la misma. Lo bueno es que en Overkill Software no se han limitado únicamente a aumentar el número de misiones y ya está, sino que también se han preocupado por hacerlas diferentes y variadas, por lo que tan pronto estaremos\
      atracando un banco, que destrozando tiendas en un centro comercial o luchando en mitad de una discoteca mientras le robamos a una banda rival.",
    
    "Fallout 4": 
      "Bethesda regresó en 2015 con este RPG postapocalíptico. Con un puntaje de 84/100, Fallout 4 combina exploración, combate y construcción de asentamientos en un mundo devastado. Es ideal para los jugadores que disfrutan de la libertad total en sus aventuras. Con Fallout 4 Bethesda sigue refinando su fórmula, la de juegos a los\
      que cada vez nos cuesta más considerar RPG, y sí aventuras en mundo abierto, algo que ya vimos de manera muy clara en The Elder Scrolls V: Skyrim (2011). Con esto no estamos diciendo que hayan desaparecido los habituales elementos de juego de rol -que por cierto han permeado en todo tipo de géneros en los últimos años-, pero\
      tenemos la sensación de que cada vez les dan menos importancia, intentando mejorar en otros aspectos como la acción, la narrativa, la ambientación y en definitiva el crear un mundo convincente y apasionante para que el jugador se lo pase en grande descubriendo todo lo que ofrece durante decenas horas. Una aventura con el inconfundible\
      sello de Bethesda, con todo lo bueno y también lo malo que ello conlleva, y quienes disfrutasteis de juegos como Fallout 3 o The Elder Scrolls V: Skyrim seguro que sabéis perfectamente de lo que estamos hablando y os hacéis una buena idea de lo que os vais a encontrar. De espíritu continuista, como le gusta a su director Todd Howard,\
      aunque con más novedades y cambios jugables de lo que parecía en un principio, casi todos para bien, aunque alguno que otro para mal, como su pírrico sistema de conversación, que ahora explicaremos.",
    
    "God of War (2018)": 
      "En un mundo de mitología nórdica, Kratos, el antiguo dios griego de la guerra, lucha por superar su pasado mientras cuida de su hijo Atreus. 'God of War' reinventa la serie con una narrativa más profunda y emocional, alejándose de la violencia desenfrenada y explorando la relación padre-hijo en medio de una guerra divina. Con\
      combates renovados, exploración detallada y una trama que toca el corazón, el juego ofrece una de las mejores experiencias en su género, todo acompañado de una impresionante dirección artística. God of War no es solo una saga de videojuegos muy querida por muchos jugadores, es uno de los buques insignia de la marca PlayStation,\
      y vuelve tras cinco años de ausencia por todo lo alto, con un auténtico juegazo, impecable y contundente en todos los aspectos. Una demostración de músculo por parte de Sony con la que reafirma su compromiso con las grandes superproducciones para un jugador, tras exclusivos para PS4 tan importantes como Uncharted 4: El Desenlace\
      del Ladrón (2016) y Horizon: Zero Dawn (2017). A veces no es necesario esperar a que algo esté muerto o agotado para reanimarlo, y eso es lo que han hecho en Santa Monica Studio con este nuevo God of War, que redefine los pilares de la saga tomando prestadas algunas de las tendencias actuales del mundo de los videojuegos, pero que\
      a su vez conecta perfectamente con las entregas anteriores y recupera sus mayores virtudes, siendo finalmente más similar a las primeras aventuras de Kratos de lo que muchos se esperaban.",
    
    "Team Fortress 2": 
      "Valve estableció el estándar del multijugador en 2007 con este título lleno de humor y acción. Con un puntaje de 92/100, TF2 ofrece clases únicas, mapas dinámicos y un estilo visual que lo ha mantenido relevante durante más de una década. Y es que Team Fortress 2 es un título de acción multijugador en el que prima la acción directa,\
      sin obviar un elemento táctico basado en la elección de clases y nuestra estrategia a la hora de afrontar las partidas. La rapidez con la que entramos en acción es asombrosa. Elegimos equipo –rojo o azul–, elegimos clase y a jugar. Es como el ajedrez, se tarda muy poco tiempo en aprender las reglas, pero requiere esfuerzo y dedicación\
      llegar a dominar cada pieza. En la variedad está el gusto. Si hay una pieza clave en la que se basa la jugabilidad, es la variedad de clases de los combatientes. Hay un total de nueve y cada una se presta a una estrategia determinada. Dependiendo del mapa en el que estemos, el modo de juego e incluso las circunstancias de la partida,\
      será idóneo elegir entre unos y otros. Y no sólo eso; si nos matan podremos cambiar de clase, ya que nos podría interesar optar por una opción determinada para superar un contratiempo puntual. Por poner un ejemplo: estamos luchando como 'pyro' y no podemos superar una zona por culpa de un par de armas centinela. En ese caso sería una\
      buena idea elegir un soldado equipado con lanzacohetes para destruirlas, aunque como veréis más adelante, las posibilidades son muchísimo más amplias.",
    
    "Limbo": 
      "Playdead lanzó este juego en 2010, cautivando a jugadores con su atmósfera sombría y minimalista. Con un puntaje de 90/100, combina acertijos desafiantes con una narrativa intrigante que deja una impresión duradera. El desarrollo es el de un plataformas bidimensional, pero pasado por una apuesta estética de ensoñación siniestra en la\
      que se juega con múltiples capas de diferentes tonalidades de gris, empezando por un entorno natural, un bosque lleno de peligros, pero vivo y orgánico, que luego dará paso a un entorno industrial frío, muerto, donde los peligros son menores, pero los puzles ganan en importancia. Pero esta ensoñación es más bien una pesadilla oscura,\
      en la que un paso en falso implica una muerte cruel. Es tan fácil que un cepo te reviente, como ser aplastado por una roca, como morir ahogado, como caer en decenas y decenas de trampas que debemos sortear con habilidad y la capacidad resolutiva necesaria para superar los puzles. Además, la muerte es instantánea, lo que convierte a Limbo\
      en un juego de prueba y error. Pero no por ello es frustrante; al morir aparecemos realmente cerca de la prueba o enemigo que nos mató, dispuestos a intentarlo de nuevo. Se pierde poco tiempo, y la sensación es que no resulta frustrante en absoluto. Es importante, porque algunos puzles no son en absoluto obvios, y hay fragmentos que\
      requieren mucha precisión y habilidad."
};

export default customDescriptions;